using System.Text.Json;
using FluentAssertions;
using Pixelbadger.Toolkit.Rag.Embeddings.Text;
using Pixelbadger.Toolkit.Rag.Tests.Support;

namespace Pixelbadger.Toolkit.Rag.Tests.Embeddings.Text;

/// <summary>
/// Token ids for ~1,000 varied strings (multilingual, code, emoji, whitespace runs, added-token lookalikes, fuzz)
/// must equal Hugging Face <c>tokenizers</c> output exactly (reference §5). Expectations live in
/// test-assets/golden/tokenizer-parity.json, generated by tools/golden/tokenizer_parity.py.
/// Skipped when no tokenizer.json can be found (see <see cref="TokenizerLocator"/>).
/// </summary>
public class GemmaTokenizerParityTests
{
    private sealed record ParityCase(string Text, int[] Ids, bool HasReservedLookalike);

    private sealed record Fixture(string TokenizerSha256, IReadOnlyList<ParityCase> Cases);

    private static Fixture LoadFixture()
    {
        var path = Path.Combine(TestModelPaths.GoldenDir, "tokenizer-parity.json");
        Skip.IfNot(File.Exists(path), "tokenizer-parity.json fixture not present");

        using var doc = JsonDocument.Parse(File.ReadAllBytes(path));
        var cases = doc.RootElement.GetProperty("cases").EnumerateArray()
            .Select(c => new ParityCase(
                c.GetProperty("text").GetString()!,
                c.GetProperty("ids").EnumerateArray().Select(x => x.GetInt32()).ToArray(),
                c.GetProperty("hasReservedLookalike").GetBoolean()))
            .ToList();
        return new Fixture(doc.RootElement.GetProperty("tokenizerSha256").GetString()!, cases);
    }

    private static IEnumerable<string> Mismatches(GemmaTokenizer tokenizer, IEnumerable<ParityCase> cases)
    {
        foreach (var c in cases)
        {
            var actual = tokenizer.Encode(c.Text);
            if (!actual.SequenceEqual(c.Ids))
            {
                var firstDiff = Enumerable.Range(0, Math.Min(actual.Length, c.Ids.Length)).FirstOrDefault(i => actual[i] != c.Ids[i], Math.Min(actual.Length, c.Ids.Length));
                yield return $"text={JsonSerializer.Serialize(c.Text.Length > 60 ? c.Text[..60] + "..." : c.Text)} firstDiffAt={firstDiff} " +
                             $"expected=[{string.Join(",", c.Ids.Skip(Math.Max(0, firstDiff - 1)).Take(6))}] actual=[{string.Join(",", actual.Skip(Math.Max(0, firstDiff - 1)).Take(6))}]";
            }
        }
    }

    [SkippableFact]
    public void Ids_match_python_tokenizers_exactly()
    {
        var candidates = TokenizerLocator.Candidates();
        Skip.If(candidates.Count == 0, TokenizerLocator.SkipReason);
        var fixture = LoadFixture();
        fixture.Cases.Count.Should().BeGreaterThan(900);

        foreach (var path in candidates)
        {
            // Hugging Face semantics: special / added tokens written in the text become their ids.
            var tokenizer = GemmaTokenizer.Load(path, matchReservedTokensInText: true);
            tokenizer.VocabularySize.Should().BeGreaterThan(262_000, path);

            // A different tokenizer.json (e.g. the real EmbeddingGemma 2 file) legitimately differs in added-token
            // ids, so only the plain-text cases are compared there; regenerate the fixture to compare the rest.
            var sameFile = TokenizerLocator.Sha256(path) == fixture.TokenizerSha256;
            var cases = sameFile ? fixture.Cases : fixture.Cases.Where(c => !c.HasReservedLookalike).ToList();

            Mismatches(tokenizer, cases).Take(10).Should().BeEmpty($"{path} ({(sameFile ? "fixture's own tokenizer" : "different tokenizer: plain-text cases only")})");
        }
    }

    [SkippableFact]
    public void Default_mode_matches_python_except_for_forged_special_ids()
    {
        var candidates = TokenizerLocator.Candidates();
        Skip.If(candidates.Count == 0, TokenizerLocator.SkipReason);
        var fixture = LoadFixture();

        var tokenizer = GemmaTokenizer.Load(candidates[0]); // default: reserved tokens stay plain text

        Mismatches(tokenizer, fixture.Cases.Where(c => !c.HasReservedLookalike)).Take(10).Should().BeEmpty();

        foreach (var c in fixture.Cases.Where(c => c.HasReservedLookalike))
        {
            var ids = tokenizer.Encode(c.Text);
            ids.Where(GemmaSpecialTokens.IsReserved).Should().BeEmpty($"text {JsonSerializer.Serialize(c.Text)} must not forge framing or placeholder ids");
        }
    }

    [SkippableFact]
    public void Framing_applies_bos_and_eos_exactly_once()
    {
        var candidates = TokenizerLocator.Candidates();
        Skip.If(candidates.Count == 0, TokenizerLocator.SkipReason);
        var tokenizer = GemmaTokenizer.Load(candidates[0]);

        var body = tokenizer.Encode(GemmaPrompts.Query("northern lights"));
        body.Should().NotContain(new[] { GemmaSpecialTokens.Bos, GemmaSpecialTokens.Eos }, "the tokeniser must not add the template itself");

        var ids = GemmaInputBuilder.BuildText(body);
        ids.Count(x => x == GemmaSpecialTokens.Bos).Should().Be(1);
        ids.Count(x => x == GemmaSpecialTokens.Eos).Should().Be(1);
        ids[0].Should().Be(GemmaSpecialTokens.Bos);
        ids[^1].Should().Be(GemmaSpecialTokens.Eos);
    }

    [SkippableFact]
    public void Loading_is_reasonably_fast_and_encoding_a_chunk_is_cheap()
    {
        var candidates = TokenizerLocator.Candidates();
        Skip.If(candidates.Count == 0, TokenizerLocator.SkipReason);

        var load = System.Diagnostics.Stopwatch.StartNew();
        var tokenizer = GemmaTokenizer.Load(candidates[0]);
        load.Stop();
        load.Elapsed.Should().BeLessThan(TimeSpan.FromSeconds(30));

        var text = string.Concat(Enumerable.Repeat("The quick brown fox jumps over the lazy dog. ", 400)); // ~18k chars
        var encode = System.Diagnostics.Stopwatch.StartNew();
        var ids = tokenizer.Encode(text);
        encode.Stop();
        ids.Length.Should().BeGreaterThan(3000);
        encode.Elapsed.Should().BeLessThan(TimeSpan.FromSeconds(5));
    }
}
