// <auto-generated />
using System;
using Microsoft.Data.SqlTypes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pixelbadger.Toolkit.Rag.Persistence;

#nullable disable

namespace Pixelbadger.Toolkit.Rag.Migrations
{
    [DbContext(typeof(RagDbContext))]
    partial class RagDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pixelbadger.Toolkit.Rag.Domain.Chunk", b =>
                {
                    b.Property<int>("ChunkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChunkId"));

                    b.Property<string>("ChunkText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<SqlVector<float>>("Embedding")
                        .HasColumnType("vector(256)");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("GlobalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("LocatorEnd")
                        .HasColumnType("bigint");

                    b.Property<long?>("LocatorStart")
                        .HasColumnType("bigint");

                    b.Property<byte>("Modality")
                        .HasColumnType("tinyint");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.HasKey("ChunkId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("ChunkId"));

                    b.HasIndex("GlobalId")
                        .IsUnique();

                    b.HasIndex("DocumentId", "Ordinal")
                        .HasDatabaseName("IX_Chunks_Doc");

                    b.ToTable("Chunks_EG2_256", (string)null);
                });

            modelBuilder.Entity("Pixelbadger.Toolkit.Rag.Domain.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("char(64)");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("GlobalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("IndexStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Modality")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("SourceContent")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("DocumentId");

                    b.HasIndex("GlobalId")
                        .IsUnique();

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("Pixelbadger.Toolkit.Rag.Domain.IngestJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<int?>("ChunkCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LeaseExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeaseOwner")
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LogicalPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("MaxChunkCharacters")
                        .HasColumnType("int");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "CreatedAtUtc")
                        .HasDatabaseName("IX_IngestJobs_Document_CreatedAtUtc");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("IX_IngestJobs_Status_CreatedAtUtc");

                    b.ToTable("IngestJobs", (string)null);
                });

            modelBuilder.Entity("Pixelbadger.Toolkit.Rag.Domain.Chunk", b =>
                {
                    b.HasOne("Pixelbadger.Toolkit.Rag.Domain.Document", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Pixelbadger.Toolkit.Rag.Domain.IngestJob", b =>
                {
                    b.HasOne("Pixelbadger.Toolkit.Rag.Domain.Document", "Document")
                        .WithMany("Jobs")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Pixelbadger.Toolkit.Rag.Domain.Document", b =>
                {
                    b.Navigation("Chunks");

                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
