using System.Text.Json;
using FluentAssertions;
using Pixelbadger.Toolkit.Rag.Embeddings.Text;
using Pixelbadger.Toolkit.Rag.Tests.Support;

namespace Pixelbadger.Toolkit.Rag.Tests.Golden;

/// <summary>
/// End-to-end checks against fixtures generated by tools/golden/generate.mjs (transformers.js on the same ONNX files).
/// Every test skips unless PBRAG_MODEL_PATH is set and the fixtures exist, so CI without the model stays green.
/// Tolerances: ids exact, tensors atol 1e-4, final embedding cosine &gt;= 0.9999.
/// </summary>
public class EmbeddingGemmaGoldenTests
{
    private const double MinCosine = 0.9999;
    private const float TensorTolerance = 1e-4f;

    private sealed record TextFixture(string[] Queries, (string? Title, string Text)[] Documents)
    {
        public static TextFixture Load()
        {
            using var doc = JsonDocument.Parse(File.ReadAllBytes(GoldenFixtures.PathOf("txt.texts.json")));
            return new TextFixture(
                doc.RootElement.GetProperty("queries").EnumerateArray().Select(x => x.GetString()!).ToArray(),
                doc.RootElement.GetProperty("documents").EnumerateArray()
                    .Select(d => (d.GetProperty("title").GetString(), d.GetProperty("text").GetString()!)).ToArray());
        }
    }

    // ----------------------------------------------------------------------------------------------- text

    [SkippableFact]
    public void Text_input_ids_match_the_reference_processor_exactly()
    {
        var modelPath = GoldenFixtures.RequireModelAndFixtures();
        var fixture = TextFixture.Load();
        var tokenizer = GemmaTokenizer.Load(Path.Combine(modelPath, "tokenizer.json"));

        var ids = GoldenFixtures.Tensor("txt", "input_ids");
        var mask = GoldenFixtures.Tensor("txt", "attention_mask");
        var all = ids.AsInt64();
        var m = mask.AsInt64();
        var rows = ids.Dims[0];
        var width = ids.Dims[1];

        var prompts = fixture.Queries.Select(GemmaPrompts.Query)
            .Concat(fixture.Documents.Select(d => GemmaPrompts.Document(d.Title, d.Text))).ToArray();
        prompts.Length.Should().Be(rows);

        for (int r = 0; r < rows; r++)
        {
            var expected = Enumerable.Range(0, width).Where(j => m[r * width + j] == 1).Select(j => all[r * width + j]).ToArray();
            var actual = GemmaInputBuilder.BuildText(tokenizer.Encode(prompts[r]));
            actual.Should().Equal(expected, $"row {r}: {prompts[r][..Math.Min(40, prompts[r].Length)]}");
        }
    }

    [SkippableFact]
    public async Task Text_embeddings_match_the_reference_model()
    {
        var modelPath = GoldenFixtures.RequireModelAndFixtures();
        var fixture = TextFixture.Load();
        using var services = GoldenFixtures.BuildServices(modelPath);
        var embeddings = GoldenFixtures.Embeddings(services);

        var golden = GoldenFixtures.Tensor("txt", "embedding");
        golden.Dims.Should().Equal(fixture.Queries.Length + fixture.Documents.Length, 768);
        var flat = golden.AsFloat();
        float[] Row(int i) => GoldenFixtures.Truncated(flat[(i * 768)..((i + 1) * 768)]);

        for (int q = 0; q < fixture.Queries.Length; q++)
        {
            var vector = await embeddings.EmbedQueryAsync(fixture.Queries[q]);
            GoldenFixtures.Cosine(vector, Row(q)).Should().BeGreaterThanOrEqualTo(MinCosine, $"query {q}: {fixture.Queries[q]}");
        }

        for (int d = 0; d < fixture.Documents.Length; d++)
        {
            var (title, text) = fixture.Documents[d];
            var vector = (await embeddings.EmbedDocumentTextAsync(title, new[] { text }))[0];
            GoldenFixtures.Cosine(vector, Row(fixture.Queries.Length + d)).Should().BeGreaterThanOrEqualTo(MinCosine, $"document {d}: {title}");
        }
    }

    [SkippableFact]
    public async Task Batched_documents_equal_one_at_a_time()
    {
        var modelPath = GoldenFixtures.RequireModelAndFixtures();
        var fixture = TextFixture.Load();
        using var services = GoldenFixtures.BuildServices(modelPath);
        var embeddings = GoldenFixtures.Embeddings(services);

        var texts = fixture.Documents.Select(d => d.Text).ToArray();
        var batched = await embeddings.EmbedDocumentTextAsync("shared.md", texts);
        for (int i = 0; i < texts.Length; i++)
        {
            var single = (await embeddings.EmbedDocumentTextAsync("shared.md", new[] { texts[i] }))[0];
            GoldenFixtures.Cosine(batched[i], single).Should().BeGreaterThanOrEqualTo(MinCosine, $"document {i}: padding must not change the vector");
        }
    }

    /// <summary>Model card sanity check: Mars must rank first; scores are for the 768-d vectors, so allow slack at 256.</summary>
    [SkippableFact]
    public async Task Red_planet_sanity_check_ranks_mars_first()
    {
        var modelPath = GoldenFixtures.RequireModelAndFixtures();
        using var services = GoldenFixtures.BuildServices(modelPath);
        var embeddings = GoldenFixtures.Embeddings(services);

        var query = await embeddings.EmbedQueryAsync("Which planet is known as the Red Planet?");
        var docs = await embeddings.EmbedDocumentTextAsync(null, new[]
        {
            "Venus is often called Earth's twin because of its similar size and proximity.",
            "Mars, known for its reddish appearance, is often referred to as the Red Planet.",
            "Jupiter, the largest planet in our solar system, has a prominent red spot.",
            "Saturn, famous for its rings, is sometimes mistaken for the Red Planet.",
        });

        var scores = docs.Select(d => GoldenFixtures.Cosine(query, d)).ToArray();
        var expected768 = new[] { 0.675, 0.853, 0.747, 0.778 }; // Venus, Mars, Jupiter, Saturn

        scores.Select((s, i) => (s, i)).OrderByDescending(x => x.s).Select(x => x.i)
            .Should().Equal(new[] { 1, 3, 2, 0 }, $"ranking Mars > Saturn > Jupiter > Venus; scores {string.Join(" ", scores.Select(s => s.ToString("0.000")))}");
        for (int i = 0; i < 4; i++)
            scores[i].Should().BeApproximately(expected768[i], 0.05, $"doc {i} (256-d vs the card's 768-d score)");
    }

    // ----------------------------------------------------------------------------------------------- image

    [SkippableTheory]
    [InlineData("img-square", "img-square.png")]
    [InlineData("img-wide", "img-wide.png")]
    public async Task Image_preprocessing_ids_and_embedding_match_the_reference(string caseName, string file)
    {
        var modelPath = GoldenFixtures.RequireModelAndFixtures();
        using var services = GoldenFixtures.BuildServices(modelPath);

        var image = await GoldenFixtures.ImagePreprocessor(services).PreprocessAsync(GoldenFixtures.PathOf(file));

        // Tensors fed to vision_encoder_quantized.onnx (settles patch scan order, flatten order, position-id order, resize).
        var pixels = GoldenFixtures.Tensor(caseName, "pixel_values");
        pixels.Dims.Should().Equal(1, image.NumPatches, 768);
        GoldenFixtures.AssertClose(image.PixelValues, pixels.AsFloat(), TensorTolerance, $"{caseName} pixel_values");

        var positions = GoldenFixtures.Tensor(caseName, "pixel_position_ids");
        image.PositionIds.Should().Equal(positions.AsInt64(), $"{caseName} pixel_position_ids");

        // input_ids with expanded placeholders: exact.
        var ids = GoldenFixtures.Tensor(caseName, "input_ids").AsInt64();
        GemmaInputBuilder.BuildImage(image.ExpectedSoftTokens).Should().Equal(ids, $"{caseName} input_ids");

        // Final embedding.
        var vector = await GoldenFixtures.Embeddings(services).EmbedImageAsync(image);
        var golden = GoldenFixtures.Truncated(GoldenFixtures.Tensor(caseName, "embedding").AsFloat());
        GoldenFixtures.Cosine(vector, golden).Should().BeGreaterThanOrEqualTo(MinCosine, $"{caseName} embedding");
    }

    // ----------------------------------------------------------------------------------------------- audio

    [SkippableTheory]
    [InlineData("aud-short", "aud-short.wav", 1)]
    [InlineData("aud-multiclip", "aud-multiclip.wav", 3)] // exactly 30 s: one window, three 11.2 s clips
    public async Task Audio_preprocessing_ids_and_embedding_match_the_reference(string caseName, string file, int expectedClips)
    {
        var modelPath = GoldenFixtures.RequireModelAndFixtures();
        using var services = GoldenFixtures.BuildServices(modelPath);

        var windows = await GoldenFixtures.AudioPreprocessor(services).PreprocessAsync(GoldenFixtures.PathOf(file));
        windows.Should().ContainSingle("the fixture is at most one 30 s window");
        var audio = windows[0].Features;
        audio.Clips.Should().Be(expectedClips);

        var features = GoldenFixtures.Tensor(caseName, "input_features");
        features.Dims.Should().Equal(audio.Clips, audio.Frames, PreprocessedAudioMelBins);
        GoldenFixtures.AssertClose(audio.InputFeatures, features.AsFloat(), TensorTolerance, $"{caseName} input_features");

        var mask = GoldenFixtures.Tensor(caseName, "input_features_mask");
        audio.Mask.Should().Equal(mask.AsBool(), $"{caseName} input_features_mask");

        // Placeholder count = rows the audio encoder emits for these clips; compare against the reference's input_ids.
        var ids = GoldenFixtures.Tensor(caseName, "input_ids").AsInt64();
        var placeholders = ids.Count(x => x == GemmaSpecialTokens.AudioPlaceholder);
        GemmaInputBuilder.BuildAudio(placeholders).Should().Equal(ids, $"{caseName} input_ids");

        var vector = await GoldenFixtures.Embeddings(services).EmbedAudioAsync(audio);
        var golden = GoldenFixtures.Truncated(GoldenFixtures.Tensor(caseName, "embedding").AsFloat());
        GoldenFixtures.Cosine(vector, golden).Should().BeGreaterThanOrEqualTo(MinCosine, $"{caseName} embedding");
    }

    private const int PreprocessedAudioMelBins = Pixelbadger.Toolkit.Rag.Embeddings.Audio.PreprocessedAudio.MelBins;
}
