namespace Pixelbadger.Toolkit.Rag.Tests.Support;

/// <summary>
/// Real-model tests run only when PBRAG_MODEL_PATH points at a local
/// onnx-community/embeddinggemma-2-ONNX snapshot. Use with [SkippableFact]:
/// <c>Skip.If(TestModelPaths.ModelPath is null, TestModelPaths.SkipReason);</c>
/// </summary>
public static class TestModelPaths
{
    public const string SkipReason = "PBRAG_MODEL_PATH not set (EmbeddingGemma 2 ONNX snapshot required)";

    public static string? ModelPath
    {
        get
        {
            var path = Environment.GetEnvironmentVariable("PBRAG_MODEL_PATH");
            return !string.IsNullOrWhiteSpace(path) && Directory.Exists(path) ? path : null;
        }
    }

    /// <summary>Golden fixtures generated by tools/golden (committed under test-assets/golden).</summary>
    public static string GoldenDir => Path.Combine(AppContext.BaseDirectory, "test-assets", "golden");
}
